# conda env create -f environment.yml
# conda env update -f environment.yml

name: supervised_learning_final
dependencies:
  - python==3.10
  - pip
  - pip:
    - pandas==2.0.2
    - matplotlib==3.7.2
    - seaborn==0.12.2
    - scikit-learn==1.3.0
